#include "MyManagerDef.h"

DEFINE_LOG_CATEGORY(Log_Base);
DEFINE_LOG_CATEGORY(Log_Frame);
DEFINE_LOG_CATEGORY(Log_Print);

DEFINE_LOG_CATEGORY(Log_Lua);
DEFINE_LOG_CATEGORY(Log_Logic);
DEFINE_LOG_CATEGORY(Log_Event);
DEFINE_LOG_CATEGORY(Log_UI);
DEFINE_LOG_CATEGORY(Log_Server);
DEFINE_LOG_CATEGORY(Log_Data);